### ISSUE TITLE
运行代码出现OOM问题

### ISSUE THREAD

**Issue by Natsuyu** [chencodeX/RNN_Pytorch#2]
您好，我更改了卷积核的一些参数，放在GPU上面跑，出现了Out Of Memory问题，已经把数据量改小了，按理GPU也是够用的，找不到问题在哪儿。不知道您在运行代码的时候是否有这些问题？

**Comment by chencodeX** [comment]
你用的是哪个模型

**Comment by Natsuyu** [comment]
用的HKO_model中的模型，现在问题已经解决了，之前把input_num_seqs和batch_size设置错了，但是改过之后也用了8G多的显存…还是十分感谢！

**Comment by chencodeX** [comment]
没事，诸事细心
